// seed.ts
import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import dotenv from 'dotenv';

dotenv.config();

// Import all models
import User from './models/User';
import Student from './models/Student';
import Major from './models/Major';
import Activity from './models/Activity';
import Learn from './models/Learn';
import Problem from './models/Problem';
import { Referral, Coordination, FollowUp } from './models/Send';

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/advisor';

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing data
    await Promise.all([
      User.deleteMany({}),
      Student.deleteMany({}),
      Major.deleteMany({}),
      Activity.deleteMany({}),
      Learn.deleteMany({}),
      Problem.deleteMany({}),
      Referral.deleteMany({}),
      Coordination.deleteMany({}),
      FollowUp.deleteMany({}),
    ]);
    console.log('🗑️  Cleared existing data');

    // ==================== CREATE MAJORS ====================
    console.log('\n📚 Creating majors...');
    const majors = await Major.insertMany([
      { major_id: 1, major_name: 'เทคโนโลยีสารสนเทศ' },
      { major_id: 2, major_name: 'คอมพิวเตอร์ธุรกิจ' },
      { major_id: 3, major_name: 'การบัญชี' },
      { major_id: 4, major_name: 'การตลาด' },
      { major_id: 5, major_name: 'การโรงแรม' },
      { major_id: 6, major_name: 'ช่างไฟฟ้ากำลัง' },
      { major_id: 7, major_name: 'ช่างกลโรงงาน' },
      { major_id: 8, major_name: 'ช่างเชื่อมโลหะ' },
      { major_id: 9, major_name: 'อาหารและโภชนาการ' },
    ]);

    // ==================== CREATE USERS ====================
    console.log('👥 Creating users...');
    const hashedPassword = await bcrypt.hash('1234', 10);
    
    const [admin, teacher1, teacher2, teacher3, executive, committee] = await User.create([
      {
        email: 'admin@school.ac.th',
        password: hashedPassword,
        provider: 'credentials',
        prefix: 'นาย',
        first_name: 'สมชาย',
        last_name: 'บริหารงาน',
        nickname: 'ชาย',
        teacher_id: 'T001',
        phone: '081-234-5678',
        line_id: 'admin_line',
        role: 'ADMIN',
        is_active: true,
        department: 'บริหาร',
        last_login: new Date('2024-03-13T08:30:00'),
      },
      {
        email: 'somsak@school.ac.th',
        password: hashedPassword,
        provider: 'credentials',
        prefix: 'นาย',
        first_name: 'สมศักดิ์',
        last_name: 'ที่ปรึกษาดี',
        nickname: 'ศักดิ์',
        teacher_id: 'T002',
        phone: '082-345-6789',
        line_id: 'somsak_line',
        role: 'TEACHER',
        is_active: true,
        homeroom_level: 'ปวช.1',
        homeroom_class: 'เทคโนโลยีสารสนเทศ',
        department: 'เทคโนโลยีสารสนเทศ',
        subject_specialization: ['การเขียนโปรแกรม', 'ฐานข้อมูล'],
        last_login: new Date('2024-03-13T09:15:00'),
      },
      {
        email: 'malee@school.ac.th',
        password: hashedPassword,
        provider: 'credentials',
        prefix: 'นางสาว',
        first_name: 'มาลี',
        last_name: 'ดูแลดี',
        nickname: 'ลี',
        teacher_id: 'T003',
        phone: '083-456-7890',
        line_id: 'malee_line',
        role: 'TEACHER',
        is_active: true,
        homeroom_level: 'ปวช.2',
        homeroom_class: 'การบัญชี',
        department: 'การบัญชี',
        subject_specialization: ['การบัญชีขั้นต้น', 'ภาษีอากร'],
        last_login: new Date('2024-03-13T08:45:00'),
      },
      {
        email: 'prasert@school.ac.th',
        password: hashedPassword,
        provider: 'credentials',
        prefix: 'นาย',
        first_name: 'ประเสริฐ',
        last_name: 'บริหารสูง',
        nickname: 'เสริฐ',
        teacher_id: 'T004',
        phone: '084-567-8901',
        line_id: 'prasert_line',
        role: 'TEACHER',
        is_active: true,
        homeroom_level: 'ปวส.1',
        homeroom_class: 'การตลาด',
        department: 'การตลาด',
        subject_specialization: ['การตลาดดิจิทัล', 'การขาย'],
        last_login: new Date('2024-03-13T10:00:00'),
      },
      {
        email: 'executive@school.ac.th',
        password: hashedPassword,
        provider: 'credentials',
        prefix: 'นาง',
        first_name: 'วิไลวรรณ',
        last_name: 'ผู้อำนวยการ',
        nickname: 'วิ',
        teacher_id: 'T005',
        phone: '085-678-9012',
        role: 'EXECUTIVE',
        is_active: true,
        department: 'ฝ่ายบริหาร',
        last_login: new Date('2024-03-13T08:00:00'),
      },
      {
        email: 'committee@school.ac.th',
        password: hashedPassword,
        provider: 'credentials',
        prefix: 'นาย',
        first_name: 'ประพันธ์',
        last_name: 'กรรมการ',
        nickname: 'พันธ์',
        teacher_id: 'T006',
        phone: '086-789-0123',
        role: 'COMMITTEE',
        is_active: true,
        department: 'คณะกรรมการสถานศึกษา',
        last_login: new Date('2024-03-12T14:30:00'),
      },
    ]);

    // ==================== CREATE STUDENTS ====================
    console.log('🎓 Creating students...');
    
    // Teacher 1's students (ปวช.1 - เทคโนโลยีสารสนเทศ)
    const students_teacher1 = await Student.create([
      {
        id: '66001',
        prefix: 'นาย',
        first_name: 'ณัฐพล',
        last_name: 'มีสุข',
        nickname: 'พล',
        email: 'nattapon.m@student.ac.th',
        phone_number: '091-234-5678',
        gender: 'ชาย',
        birth_date: '2006-05-15',
        level: 'ปวช.1',
        class_group: 'เทคโนโลยีสารสนเทศ',
        class_number: '1',
        advisor_id: teacher1._id.toString(),
        advisor_name: 'นายสมศักดิ์ ที่ปรึกษาดี',
        religion: 'พุทธ',
        address: '123 หมู่ 2 ต.ในเมือง อ.เมือง จ.ขอนแก่น 40000',
        weight: '65',
        height: '170',
        bmi: '22.5',
        blood_type: 'O',
        status: 'ปกติ',
        semester: '2',
        academic_year: '2567',
        parent_name: 'สมชาย มีสุข',
        parent_relationship: 'บิดา',
        parent_phone: '081-111-2222',
        family_status: ['อยู่ด้วยกัน'],
        living_with: 'บิดา-มารดา',
        housing_type: 'บ้านตนเอง',
        transportation: ['รถส่วนตัว'],
        strengths: 'เรียนดี ชอบช่วยเหลือเพื่อน',
        weak_subjects: 'คณิตศาสตร์',
        hobbies: 'เล่นกีฬา ฟังเพลง',
        home_behavior: 'ช่วยงานบ้าน',
        chronic_disease: 'ภูมิแพ้',
        risk_behaviors: [],
        parent_concerns: 'อยากให้ตั้งใจเรียนมากขึ้น',
        family_income: '25000',
        daily_allowance: '100',
        assistance_needs: ['ทุนการศึกษา'],
        student_group: 'ปกติ',
        help_guidelines: 'ส่งเสริมความสามารถพิเศษด้านกีฬา',
        home_visit_files: [],
        image: '',
        dass21: {
          depression: 5,
          anxiety: 4,
          stress: 6,
          total: 15,
          level: 'ปกติ'
        },
        sdq: {
          emotional: 2,
          conduct: 1,
          hyperactivity: 3,
          peer: 1,
          prosocial: 8,
          total: 7,
          level: 'ปกติ'
        },
        created_at: new Date('2023-05-10'),
        updated_at: new Date('2024-03-10'),
      },
      {
        id: '66002',
        prefix: 'นางสาว',
        first_name: 'จิราภา',
        last_name: 'ใจดี',
        nickname: 'จิ',
        email: 'jirapa.j@student.ac.th',
        phone_number: '092-345-6789',
        gender: 'หญิง',
        birth_date: '2006-08-20',
        level: 'ปวช.1',
        class_group: 'เทคโนโลยีสารสนเทศ',
        class_number: '2',
        advisor_id: teacher1._id.toString(),
        advisor_name: 'นายสมศักดิ์ ที่ปรึกษาดี',
        religion: 'พุทธ',
        address: '456 หมู่ 5 ต.บ้านเป็ด อ.เมือง จ.ขอนแก่น 40000',
        weight: '55',
        height: '160',
        bmi: '21.5',
        blood_type: 'A',
        status: 'เสี่ยง',
        semester: '2',
        academic_year: '2567',
        parent_name: 'วิไล ใจดี',
        parent_relationship: 'มารดา',
        parent_phone: '082-222-3333',
        family_status: ['หย่าร้าง'],
        living_with: 'บุคคลอื่น',
        living_with_other: 'มารดา',
        housing_type: 'บ้านเช่า',
        transportation: ['รถสาธารณะ'],
        strengths: 'ขยัน รับผิดชอบ',
        weak_subjects: 'ภาษาอังกฤษ',
        hobbies: 'อ่านหนังสือ วาดรูป',
        home_behavior: 'ช่วยแม่ทำงานบ้าน',
        chronic_disease: '-',
        risk_behaviors: ['ความเครียด/ซึมเศร้า'],
        parent_concerns: 'ลูกเครียดเรื่องการเรียน',
        family_income: '12000',
        daily_allowance: '70',
        assistance_needs: ['ทุนการศึกษา', 'ค่าอาหาร'],
        student_group: 'เสี่ยง',
        help_guidelines: 'ให้คำปรึกษาด้านการเรียน หาทุนช่วยเหลือ',
        home_visit_files: [],
        image: '',
        dass21: {
          depression: 12,
          anxiety: 10,
          stress: 14,
          total: 36,
          level: 'ปานกลาง'
        },
        sdq: {
          emotional: 6,
          conduct: 2,
          hyperactivity: 4,
          peer: 3,
          prosocial: 6,
          total: 15,
          level: 'เสี่ยง'
        },
        created_at: new Date('2023-05-12'),
        updated_at: new Date('2024-03-12'),
      },
      {
        id: '66003',
        prefix: 'นาย',
        first_name: 'ธนดล',
        last_name: 'เข้มแข็ง',
        nickname: 'ดล',
        email: 'thanadon.k@student.ac.th',
        phone_number: '093-456-7890',
        gender: 'ชาย',
        birth_date: '2006-02-10',
        level: 'ปวช.1',
        class_group: 'เทคโนโลยีสารสนเทศ',
        class_number: '3',
        advisor_id: teacher1._id.toString(),
        advisor_name: 'นายสมศักดิ์ ที่ปรึกษาดี',
        religion: 'พุทธ',
        address: '789 หมู่ 3 ต.เมืองเก่า อ.เมือง จ.ขอนแก่น 40000',
        weight: '70',
        height: '172',
        bmi: '23.7',
        blood_type: 'B',
        status: 'มีปัญหา',
        semester: '2',
        academic_year: '2567',
        parent_name: 'ประเสริฐ เข้มแข็ง',
        parent_relationship: 'บิดา',
        parent_phone: '083-333-4444',
        family_status: ['อยู่ด้วยกัน'],
        living_with: 'บิดา-มารดา',
        housing_type: 'บ้านตนเอง',
        transportation: ['รถส่วนตัว'],
        strengths: 'กล้าแสดงออก มีความเป็นผู้นำ',
        weak_subjects: 'การเขียนโปรแกรม',
        hobbies: 'เล่นฟุตบอล',
        home_behavior: 'ชอบออกไปเล่นกับเพื่อน',
        chronic_disease: 'หอบหืด',
        risk_behaviors: ['ขาดเรียนบ่อย', 'ทะเลาะวิวาท'],
        parent_concerns: 'ไม่ค่อยอยู่บ้าน ติดเพื่อน',
        family_income: '35000',
        daily_allowance: '150',
        assistance_needs: [],
        student_group: 'มีปัญหา',
        help_guidelines: 'จัดกิจกรรมสร้างแรงจูงใจในการเรียน',
        home_visit_files: [],
        image: '',
        dass21: {
          depression: 18,
          anxiety: 16,
          stress: 20,
          total: 54,
          level: 'รุนแรง'
        },
        sdq: {
          emotional: 5,
          conduct: 8,
          hyperactivity: 7,
          peer: 4,
          prosocial: 4,
          total: 24,
          level: 'มีปัญหา'
        },
        created_at: new Date('2023-05-15'),
        updated_at: new Date('2024-03-13'),
      },
    ]);

    // Teacher 2's students (ปวช.2 - การบัญชี)
    const students_teacher2 = await Student.create([
      {
        id: '65001',
        prefix: 'นาย',
        first_name: 'วรเมธ',
        last_name: 'รักเรียน',
        nickname: 'เมธ',
        email: 'worameth.r@student.ac.th',
        phone_number: '095-678-9012',
        gender: 'ชาย',
        birth_date: '2005-07-18',
        level: 'ปวช.2',
        class_group: 'การบัญชี',
        class_number: '1',
        advisor_id: teacher2._id.toString(),
        advisor_name: 'นางสาวมาลี ดูแลดี',
        religion: 'พุทธ',
        address: '222 หมู่ 7 ต.บ้านหว้า อ.เมือง จ.ขอนแก่น 40000',
        weight: '68',
        height: '175',
        bmi: '22.2',
        blood_type: 'O',
        status: 'เสี่ยง',
        semester: '2',
        academic_year: '2567',
        parent_name: 'สมศักดิ์ รักเรียน',
        parent_relationship: 'บิดา',
        parent_phone: '085-555-6666',
        family_status: ['อยู่ด้วยกัน'],
        living_with: 'บิดา-มารดา',
        housing_type: 'บ้านตนเอง',
        transportation: ['รถส่วนตัว'],
        strengths: 'ชอบคอมพิวเตอร์',
        weak_subjects: 'ภาษาอังกฤษ',
        hobbies: 'เล่นเกม',
        home_behavior: 'เล่นเกมทั้งวัน',
        chronic_disease: '-',
        risk_behaviors: ['ติดเกม'],
        parent_concerns: 'เล่นเกมมากเกินไป',
        family_income: '28000',
        daily_allowance: '120',
        assistance_needs: [],
        student_group: 'เสี่ยง',
        help_guidelines: 'หากิจกรรมทดแทนการเล่นเกม',
        home_visit_files: [],
        image: '',
        dass21: {
          depression: 10,
          anxiety: 8,
          stress: 12,
          total: 30,
          level: 'ปานกลาง'
        },
        sdq: {
          emotional: 3,
          conduct: 4,
          hyperactivity: 8,
          peer: 3,
          prosocial: 5,
          total: 18,
          level: 'เสี่ยง'
        },
        created_at: new Date('2023-06-03'),
        updated_at: new Date('2024-03-08'),
      },
      {
        id: '65002',
        prefix: 'นางสาว',
        first_name: 'กนกพร',
        last_name: 'ศรีสุข',
        nickname: 'ฝน',
        email: 'kanokporn.s@student.ac.th',
        phone_number: '096-789-0123',
        gender: 'หญิง',
        birth_date: '2005-12-22',
        level: 'ปวช.2',
        class_group: 'การบัญชี',
        class_number: '2',
        advisor_id: teacher2._id.toString(),
        advisor_name: 'นางสาวมาลี ดูแลดี',
        religion: 'พุทธ',
        address: '333 หมู่ 4 ต.บึงเนียม อ.เมือง จ.ขอนแก่น 40000',
        weight: '48',
        height: '155',
        bmi: '20.0',
        blood_type: 'A',
        status: 'ปกติ',
        semester: '2',
        academic_year: '2567',
        parent_name: 'ประพันธ์ ศรีสุข',
        parent_relationship: 'บิดา',
        parent_phone: '086-666-7777',
        family_status: ['อยู่ด้วยกัน'],
        living_with: 'บิดา-มารดา',
        housing_type: 'บ้านตนเอง',
        transportation: ['รถสาธารณะ'],
        strengths: 'ขยัน อดทน',
        weak_subjects: 'การบัญชีขั้นต้น',
        hobbies: 'ฟังเพลง',
        home_behavior: 'ช่วยแม่ทำงานบ้าน',
        chronic_disease: 'โรคกระเพาะ',
        risk_behaviors: [],
        parent_concerns: 'ลูกผอมมาก อยากให้กินข้าวเยอะๆ',
        family_income: '18000',
        daily_allowance: '90',
        assistance_needs: ['ค่าอาหาร'],
        student_group: 'ปกติ',
        help_guidelines: 'ติดตามสุขภาพ โภชนาการ',
        home_visit_files: [],
        image: '',
        dass21: {
          depression: 4,
          anxiety: 5,
          stress: 4,
          total: 13,
          level: 'ปกติ'
        },
        sdq: {
          emotional: 3,
          conduct: 1,
          hyperactivity: 2,
          peer: 2,
          prosocial: 8,
          total: 8,
          level: 'ปกติ'
        },
        created_at: new Date('2023-06-05'),
        updated_at: new Date('2024-03-12'),
      },
    ]);

    // Teacher 3's students (ปวส.1 - การตลาด)
    const students_teacher3 = await Student.create([
      {
        id: '64001',
        prefix: 'นาย',
        first_name: 'อภิสิทธิ์',
        last_name: 'ศรีสุวรรณ',
        nickname: 'อภิ',
        email: 'apisit.s@student.ac.th',
        phone_number: '098-901-2345',
        gender: 'ชาย',
        birth_date: '2004-09-10',
        level: 'ปวส.1',
        class_group: 'การตลาด',
        class_number: '1',
        advisor_id: teacher3._id.toString(),
        advisor_name: 'นายประเสริฐ บริหารสูง',
        religion: 'พุทธ',
        address: '555 หมู่ 8 ต.พระลับ อ.เมือง จ.ขอนแก่น 40000',
        weight: '75',
        height: '180',
        bmi: '23.1',
        blood_type: 'O',
        status: 'ปกติ',
        semester: '2',
        academic_year: '2567',
        parent_name: 'สมพร ศรีสุวรรณ',
        parent_relationship: 'บิดา',
        parent_phone: '088-888-9999',
        family_status: ['อยู่ด้วยกัน'],
        living_with: 'บิดา-มารดา',
        housing_type: 'บ้านตนเอง',
        transportation: ['รถส่วนตัว'],
        strengths: 'มีความรับผิดชอบสูง',
        weak_subjects: 'การตลาดดิจิทัล',
        hobbies: 'เขียนโปรแกรม',
        home_behavior: 'ชอบอยู่บ้าน',
        chronic_disease: '-',
        risk_behaviors: [],
        parent_concerns: 'ไม่มี',
        family_income: '45000',
        daily_allowance: '150',
        assistance_needs: [],
        student_group: 'ปกติ',
        help_guidelines: 'ส่งเสริมด้านวิชาการ',
        home_visit_files: [],
        image: '',
        dass21: {
          depression: 3,
          anxiety: 2,
          stress: 4,
          total: 9,
          level: 'ปกติ'
        },
        sdq: {
          emotional: 1,
          conduct: 1,
          hyperactivity: 2,
          peer: 1,
          prosocial: 9,
          total: 5,
          level: 'ปกติ'
        },
        created_at: new Date('2023-06-15'),
        updated_at: new Date('2024-03-11'),
      },
      {
        id: '64002',
        prefix: 'นางสาว',
        first_name: 'วาสนา',
        last_name: 'รุ่งเรือง',
        nickname: 'นา',
        email: 'wasana.r@student.ac.th',
        phone_number: '099-012-3456',
        gender: 'หญิง',
        birth_date: '2004-04-25',
        level: 'ปวส.1',
        class_group: 'การตลาด',
        class_number: '2',
        advisor_id: teacher3._id.toString(),
        advisor_name: 'นายประเสริฐ บริหารสูง',
        religion: 'พุทธ',
        address: '666 หมู่ 9 ต.บ้านค้อ อ.เมือง จ.ขอนแก่น 40000',
        weight: '53',
        height: '162',
        bmi: '20.2',
        blood_type: 'A',
        status: 'เสี่ยง',
        semester: '2',
        academic_year: '2567',
        parent_name: 'สมหญิง รุ่งเรือง',
        parent_relationship: 'มารดา',
        parent_phone: '089-999-0000',
        family_status: ['หย่าร้าง'],
        living_with: 'บุคคลอื่น',
        living_with_other: 'มารดา',
        housing_type: 'บ้านเช่า',
        transportation: ['รถสาธารณะ'],
        strengths: 'ละเอียดรอบคอบ',
        weak_subjects: 'การขาย',
        hobbies: 'อ่านหนังสือ',
        home_behavior: 'เครียดบ่อย',
        chronic_disease: '-',
        risk_behaviors: ['ความเครียด/ซึมเศร้า'],
        parent_concerns: 'ลูกเครียดเรื่องการเรียนและการเงิน',
        family_income: '15000',
        daily_allowance: '80',
        assistance_needs: ['ทุนการศึกษา'],
        student_group: 'เสี่ยง',
        help_guidelines: 'ให้คำปรึกษา หาทุนช่วยเหลือ',
        home_visit_files: [],
        image: '',
        dass21: {
          depression: 14,
          anxiety: 12,
          stress: 16,
          total: 42,
          level: 'รุนแรง'
        },
        sdq: {
          emotional: 7,
          conduct: 2,
          hyperactivity: 3,
          peer: 3,
          prosocial: 6,
          total: 15,
          level: 'เสี่ยง'
        },
        created_at: new Date('2023-06-18'),
        updated_at: new Date('2024-03-13'),
      },
    ]);

    // ==================== UPDATE TEACHER ASSIGNMENTS ====================
    console.log('📋 Updating teacher assignments...');
    
    await User.findByIdAndUpdate(teacher1._id, {
      assigned_students: students_teacher1.map(s => ({
        student_id: s._id,
        student_name: `${s.first_name} ${s.last_name}`,
        class_number: s.class_number,
        assigned_date: new Date('2023-05-10'),
        is_active: true,
      })),
    });

    await User.findByIdAndUpdate(teacher2._id, {
      assigned_students: students_teacher2.map(s => ({
        student_id: s._id,
        student_name: `${s.first_name} ${s.last_name}`,
        class_number: s.class_number,
        assigned_date: new Date('2023-06-01'),
        is_active: true,
      })),
    });

    await User.findByIdAndUpdate(teacher3._id, {
      assigned_students: students_teacher3.map(s => ({
        student_id: s._id,
        student_name: `${s.first_name} ${s.last_name}`,
        class_number: s.class_number,
        assigned_date: new Date('2023-06-15'),
        is_active: true,
      })),
    });

    // ==================== CREATE ACTIVITIES ====================
    console.log('🎯 Creating activities...');
    const allStudents = [...students_teacher1, ...students_teacher2, ...students_teacher3];
    
    const activities = await Activity.create([
      {
        name: 'ปฐมนิเทศนักศึกษาใหม่ ภาคเรียนที่ 2',
        objective: 'สร้างความสัมพันธ์และเตรียมความพร้อมนักศึกษาใหม่',
        duration: 180,
        duration_period: 'ครั้งเดียว',
        materials: 'อุปกรณ์ละลายพฤติกรรม กระดาษ ปากกา',
        steps: '1. แนะนำตัว\n2. กิจกรรมจับคู่รู้จัก\n3. กิจกรรมกลุ่มสัมพันธ์\n4. สรุปและแลกเปลี่ยน',
        ice_breaking: 'เกมจับคู่ภาพกับเพื่อน',
        group_task: 'กิจกรรมคิดสร้างสรรค์ร่วมกัน',
        debrief: 'สรุปสิ่งที่ได้เรียนรู้และนำไปใช้',
        activity_date: new Date('2024-01-10T09:00:00'),
        participants: [
          // นักเรียนที่เข้าร่วม
          {
            student_id: '66002',
            student_name: 'นางสาวจิราภา ใจดี',
            joined: true,
            joined_at: new Date('2024-01-10T09:05:00'),
          },
          {
            student_id: '66001',
            student_name: 'นายณัฐพล มีสุข',
            joined: true,
            joined_at: new Date('2024-01-10T09:03:00'),
          },
          // นักเรียนที่ไม่เข้าร่วม (ไม่มี joined_at)
          {
            student_id: '66003',
            student_name: 'นายธนดล เข้มแข็ง',
            joined: false,
          },
        ],
        total_participants: 3,
        joined_count: 2,
        created_by: teacher1.email,
        updated_by: teacher1.email,
      },
      {
        name: 'กิจกรรมพัฒนาทักษะการเรียนและการปรับตัว',
        objective: 'เสริมทักษะการเรียนและการปรับตัวในรั้วอาชีวะ',
        duration: 120,
        duration_period: 'เดือนละครั้ง',
        materials: 'ใบงาน คอมพิวเตอร์',
        steps: '1. กิจกรรม热身\n2. เรียนรู้เทคนิคการเรียน\n3. ฝึกปฏิบัติ\n4. นำเสนอ\n5. สรุป',
        ice_breaking: 'เกมทายคำศัพท์',
        group_task: 'วางแผนการเรียนร่วมกัน',
        debrief: 'แลกเปลี่ยนเทคนิคการเรียน',
        activity_date: new Date('2024-01-17T13:00:00'),
        participants: [
          {
            student_id: '65001',
            student_name: 'นายวรเมธ รักเรียน',
            joined: true,
            joined_at: new Date('2024-01-17T13:05:00'),
          },
          {
            student_id: '65002',
            student_name: 'นางสาวกนกพร ศรีสุข',
            joined: true,
            joined_at: new Date('2024-01-17T13:08:00'),
          },
        ],
        total_participants: 2,
        joined_count: 2,
        created_by: teacher2.email,
        updated_by: teacher2.email,
      },
      {
        name: 'กิจกรรมให้คำปรึกษาแบบกลุ่ม',
        objective: 'ให้นักเรียนกลุ่มเสี่ยงได้ระบายและรับคำปรึกษา',
        duration: 90,
        duration_period: 'ทุกสัปดาห์',
        materials: 'แบบประเมินความเครียด',
        steps: '1. สร้างบรรยากาศ\n2. ให้แต่ละคนเล่าปัญหา\n3. ร่วมกันหาแนวทาง\n4. สรุป',
        ice_breaking: 'กิจกรรม breathe in breathe out',
        group_task: 'ระดมความคิดช่วยเหลือเพื่อน',
        debrief: 'สรุปแนวทางและนัดหมายครั้งต่อไป',
        activity_date: new Date('2024-01-20T10:00:00'),
        participants: [
          {
            student_id: '66002',
            student_name: 'นางสาวจิราภา ใจดี',
            joined: true,
            joined_at: new Date('2024-01-20T10:05:00'),
          },
          {
            student_id: '66003',
            student_name: 'นายธนดล เข้มแข็ง',
            joined: true,
            joined_at: new Date('2024-01-20T10:10:00'),
          },
          {
            student_id: '65001',
            student_name: 'นายวรเมธ รักเรียน',
            joined: true,
            joined_at: new Date('2024-01-20T10:07:00'),
          },
          {
            student_id: '64002',
            student_name: 'นางสาววาสนา รุ่งเรือง',
            joined: true,
            joined_at: new Date('2024-01-20T10:12:00'),
          },
        ],
        total_participants: 4,
        joined_count: 4,
        created_by: teacher1.email,
        updated_by: teacher1.email,
      },
      {
        name: 'อบรมการจัดการความเครียด',
        objective: 'เสริมสร้างทักษะการจัดการความเครียด',
        duration: 150,
        duration_period: 'ครั้งเดียว',
        materials: 'เอกสารประกอบการอบรม',
        steps: '1. แบบประเมินความเครียด\n2. บรรยายให้ความรู้\n3. ฝึกปฏิบัติ\n4. สรุป',
        ice_breaking: 'เกมหายใจคลายเครียด',
        group_task: 'ฝึกการผ่อนคลาย',
        debrief: 'แลกเปลี่ยนวิธีการจัดการความเครียด',
        activity_date: new Date('2024-01-25T09:30:00'),
        participants: [
          {
            student_id: '66002',
            student_name: 'นางสาวจิราภา ใจดี',
            joined: true,
            joined_at: new Date('2024-01-25T09:35:00'),
          },
          {
            student_id: '65001',
            student_name: 'นายวรเมธ รักเรียน',
            joined: true,
            joined_at: new Date('2024-01-25T09:40:00'),
          },
          {
            student_id: '64002',
            student_name: 'นางสาววาสนา รุ่งเรือง',
            joined: true,
            joined_at: new Date('2024-01-25T09:45:00'),
          },
        ],
        total_participants: 3,
        joined_count: 3,
        created_by: teacher3.email,
        updated_by: teacher3.email,
      },
    ]);

    // ==================== CREATE LEARN PLANS (กิจกรรมโฮมรูม) ====================
    console.log('📝 Creating learn plans...');
    await Learn.create([
      {
        level: 'ปวช.1',
        semester: '2',
        academicYear: '2567',
        week: '1',
        time: '08.30-09.30 น.',
        topic: 'ปฐมนิเทศและเตรียมความพร้อม',
        objectives: ['นักเรียนรู้กฎระเบียบ', 'นักเรียนวางแผนการเรียนได้', 'สร้างสัมพันธภาพในห้องเรียน'],
        target_class_group: 'เทคโนโลยีสารสนเทศ',
        target_class_numbers: ['1', '2', '3'],
        checkAttendance: 'เช็คชื่อนักเรียน ตรวจเครื่องแต่งกาย',
        checkUniform: 'ตรวจทรงผม เครื่องแบบ',
        announceNews: 'แจ้งกำหนดการเปิดภาคเรียน กิจกรรมสำคัญ',
        warmup: 'กิจกรรมทายนิสัยจากชื่อเล่น',
        mainActivity: 'ชี้แจงกฎระเบียบ แนะนำอาจารย์ที่ปรึกษา',
        summary: 'นักเรียนจดบันทึกและสอบถามข้อสงสัย',
        trackProblems: 'สังเกตนักเรียนที่มีท่าทีไม่สนใจ',
        individualCounsel: 'พูดคุยกับนักเรียนที่มาขอคำปรึกษา',
        evalObservation: true,
        evalWorksheet: false,
        evalParticipation: true,
        materials: [
          { name: 'คู่มือนักเรียน', url: '/files/student-handbook.pdf' },
          { name: 'PowerPoint ปฐมนิเทศ', url: '/files/orientation.pptx' }
        ],
        materialsNote: 'เตรียมเอกสารแจกนักเรียน',
        suggestions: 'เพิ่มกิจกรรมละลายพฤติกรรม',
        status: 'completed',
        created_by: teacher1.email,
        activity_date: '2024-01-10',
        students_attended: '28',
        total_students: '30',
        activity_notes: 'นักเรียนให้ความสนใจดี บางคนยังซักถาม',
        activity_problems: 'นักเรียนบางคนมาสาย',
        activity_solutions: 'ตักเตือนและทำบันทึก',
        special_track: 'นัดพบนักเรียนที่มาสาย',
        evaluator: `${teacher1.first_name} ${teacher1.last_name}`,
        has_record: true,
        recorded_at: new Date('2024-01-10T10:30:00').toISOString(),
        photos: [],
        created_at: new Date('2024-01-05').toISOString(),
        updated_at: new Date('2024-01-10').toISOString(),
      },
      {
        level: 'ปวช.1',
        semester: '2',
        academicYear: '2567',
        week: '2',
        time: '08.30-09.30 น.',
        topic: 'เทคนิคการเรียนให้ประสบความสำเร็จ',
        objectives: ['นักเรียนรู้เทคนิคการอ่านหนังสือ', 'นักเรียนสามารถวางแผนการเรียนได้'],
        target_class_group: 'เทคโนโลยีสารสนเทศ',
        target_class_numbers: ['1', '2', '3'],
        checkAttendance: 'เช็คชื่อ',
        checkUniform: 'ตรวจความเรียบร้อย',
        announceNews: 'กิจกรรมสัปดาห์ห้องสมุด',
        warmup: 'เกมตอบคำถาม',
        mainActivity: 'บรรยายเทคนิคการเรียน การจดบันทึก',
        summary: 'แลกเปลี่ยนเทคนิคที่ใช้',
        trackProblems: 'สังเกตนักเรียนที่ง่วงนอน',
        individualCounsel: '-',
        evalObservation: true,
        evalWorksheet: true,
        evalParticipation: true,
        materials: [
          { name: 'เอกสารเทคนิคการเรียน', url: '/files/study-tips.pdf' }
        ],
        materialsNote: 'ถ่ายเอกสารแจก',
        suggestions: 'อาจให้นักเรียนนำเสนอเทคนิคของตนเอง',
        status: 'completed',
        created_by: teacher1.email,
        activity_date: '2024-01-17',
        students_attended: '28',
        total_students: '30',
        activity_notes: 'นักเรียนสนใจเนื้อหา มีส่วนร่วม',
        activity_problems: 'นักเรียนบางคนไม่มีสมาธิ',
        activity_solutions: 'เรียกถาม ให้มีส่วนร่วม',
        special_track: '-',
        evaluator: `${teacher1.first_name} ${teacher1.last_name}`,
        has_record: true,
        recorded_at: new Date('2024-01-17T10:15:00').toISOString(),
        photos: [],
        created_at: new Date('2024-01-12').toISOString(),
        updated_at: new Date('2024-01-17').toISOString(),
      },
      {
        level: 'ปวช.2',
        semester: '2',
        academicYear: '2567',
        week: '1',
        time: '08.30-09.30 น.',
        topic: 'วางแผนการเรียนและการทำงาน',
        objectives: ['นักเรียนวางแผนการเรียนและฝึกงานได้'],
        target_class_group: 'การบัญชี',
        target_class_numbers: ['1', '2'],
        checkAttendance: 'เช็คชื่อ',
        checkUniform: 'ตรวจเครื่องแบบ',
        announceNews: 'แจ้งตารางสอบกลางภาค',
        warmup: 'กิจกรรมวาดฝันในอนาคต',
        mainActivity: 'พูดคุยแนวทางการฝึกงาน',
        summary: 'สรุปสิ่งที่ต้องเตรียม',
        trackProblems: 'สังเกตนักเรียนที่เครียด',
        individualCounsel: 'พูดคุยนักเรียนที่กังวล',
        evalObservation: true,
        evalWorksheet: true,
        evalParticipation: true,
        materials: [
          { name: 'แบบวางแผนการฝึกงาน', url: '/files/training-plan.pdf' }
        ],
        materialsNote: 'แจกนักเรียนทุกคน',
        suggestions: 'เชิญรุ่นพี่มาแชร์ประสบการณ์',
        status: 'completed',
        created_by: teacher2.email,
        activity_date: '2024-01-11',
        students_attended: '25',
        total_students: '28',
        activity_notes: 'นักเรียนสนใจเรื่องฝึกงาน',
        activity_problems: '-',
        activity_solutions: '-',
        special_track: 'นัดปรึกษาเพิ่มเติมสำหรับเด็กที่เครียด',
        evaluator: `${teacher2.first_name} ${teacher2.last_name}`,
        has_record: true,
        recorded_at: new Date('2024-01-11T10:00:00').toISOString(),
        photos: [],
        created_at: new Date('2024-01-08').toISOString(),
        updated_at: new Date('2024-01-11').toISOString(),
      },
      {
        level: 'ปวส.1',
        semester: '2',
        academicYear: '2567',
        week: '1',
        time: '09.30-10.30 น.',
        topic: 'การเตรียมตัวสู่วัยทำงาน',
        objectives: ['นักเรียนรู้ทักษะที่จำเป็นในการทำงาน', 'นักเรียนสามารถวางแผนอาชีพได้'],
        target_class_group: 'การตลาด',
        target_class_numbers: ['1', '2'],
        checkAttendance: 'เช็คชื่อ',
        checkUniform: 'ตรวจเครื่องแบบ',
        announceNews: 'แจ้งข่าวสารการสมัครงาน',
        warmup: 'กิจกรรมจับคู่ตำแหน่งงาน',
        mainActivity: 'บรรยายทักษะที่องค์กรต้องการ',
        summary: 'สรุปและตอบข้อซักถาม',
        trackProblems: 'สังเกตนักเรียนที่กังวล',
        individualCounsel: '-',
        evalObservation: true,
        evalWorksheet: true,
        evalParticipation: true,
        materials: [
          { name: 'คู่มือการสมัครงาน', url: '/files/job-application.pdf' }
        ],
        materialsNote: 'แจกนักเรียน',
        suggestions: 'เชิญศิษย์เก่ามาเล่าประสบการณ์',
        status: 'published',
        created_by: teacher3.email,
        has_record: false,
        created_at: new Date('2024-02-10').toISOString(),
        updated_at: new Date('2024-02-10').toISOString(),
      },
    ]);

    // ==================== CREATE PROBLEMS (ISP - แผนแก้ปัญหา) ====================
    console.log('⚠️ Creating problem/ISP records...');
    
    await Problem.create([
      {
        student_id: '66002', // จิราภา
        student_name: 'นางสาวจิราภา ใจดี',
        problem: 'ฐานะทางบ้านยากจน ขาดทุนทรัพย์ ขาดแคลนอาหารกลางวัน มีความเครียดสะสม',
        goal: 'นักเรียนมีทุนการศึกษาและมีอาหารกลางวันเพียงพอ ความเครียดลดลง',
        counseling: true,
        behavioral_contract: false,
        home_visit: true,
        referral: true,
        duration: '1 ภาคเรียน',
        responsible: `${teacher1.first_name} ${teacher1.last_name}`,
        isp_status: 'กำลังดำเนินการ',
        progress: 60,
        activities: [
          {
            activity_id: activities[0]._id,
            status: 'เข้าร่วมแล้ว',
            joined_at: new Date('2024-01-10T09:03:00'),
            notes: 'เข้าร่วมกิจกรรมปฐมนิเทศ',
          },
          {
            activity_id: activities[2]._id,
            status: 'เข้าร่วมแล้ว',
            joined_at: new Date('2024-01-20T10:05:00'),
            notes: 'เข้าร่วมกลุ่มให้คำปรึกษา',
          },
          {
            activity_id: activities[3]._id,
            status: 'เข้าร่วมแล้ว',
            joined_at: new Date('2024-01-25T09:35:00'),
            notes: 'เข้าร่วมอบรมการจัดการความเครียด',
          }
        ],
        activities_status: {
          [activities[0]._id.toString()]: 'เข้าร่วมแล้ว',
          [activities[2]._id.toString()]: 'เข้าร่วมแล้ว',
          [activities[3]._id.toString()]: 'เข้าร่วมแล้ว',
        },
        activity_join_dates: {
          [activities[0]._id.toString()]: new Date('2024-01-10T09:03:00'),
          [activities[2]._id.toString()]: new Date('2024-01-20T10:05:00'),
          [activities[3]._id.toString()]: new Date('2024-01-25T09:35:00'),
        },
        activity_completed_dates: {},
        evaluations: [
          {
            evaluation_number: 1,
            improvement_level: 'เริ่มเห็นการเปลี่ยนแปลง',
            improvement_detail: 'นักเรียนมีท่าทีสดใสขึ้น มาขอคำปรึกษาบ่อยครั้ง',
            result: 'ดำเนินการต่อ',
            notes: 'ควรหาแหล่งทุนเพิ่ม',
            evaluation_date: new Date('2024-01-15'),
          },
          {
            evaluation_number: 2,
            improvement_level: 'ดีขึ้นชัดเจน',
            improvement_detail: 'ได้รับทุนช่วยเหลือแล้ว สดใสขึ้นมาก เรียนดีขึ้น',
            result: 'ดำเนินการต่อ',
            notes: 'ติดตามต่อเนื่อง',
            evaluation_date: new Date('2024-02-15'),
          }
        ],
        last_updated: new Date('2024-02-15'),
      },
      {
        student_id: '66003', // ธนดล
        student_name: 'นายธนดล เข้มแข็ง',
        problem: 'ขาดเรียนบ่อย ติดเพื่อน ไม่ค่อยสนใจการเรียน มีพฤติกรรมก้าวร้าว',
        goal: 'นักเรียนเข้าเรียนสม่ำเสมอ ปรับพฤติกรรมการเรียนดีขึ้น ลดพฤติกรรมก้าวร้าว',
        counseling: true,
        behavioral_contract: true,
        home_visit: true,
        referral: false,
        duration: '2 เดือน',
        responsible: `${teacher1.first_name} ${teacher1.last_name}`,
        isp_status: 'ปรับแผน',
        progress: 30,
        activities: [
          {
            activity_id: activities[2]._id,
            status: 'เข้าร่วมแล้ว',
            joined_at: new Date('2024-01-20T10:10:00'),
            notes: 'เข้าร่วมกลุ่มให้คำปรึกษา',
          }
        ],
        activities_status: {
          [activities[0]._id.toString()]: 'ยังไม่เข้าร่วม',
          [activities[2]._id.toString()]: 'เข้าร่วมแล้ว',
        },
        activity_join_dates: {
          [activities[2]._id.toString()]: new Date('2024-01-20T10:10:00'),
        },
        activity_completed_dates: {},
        evaluations: [
          {
            evaluation_number: 1,
            improvement_level: 'คงเดิม/ไม่เปลี่ยนแปลง',
            improvement_detail: 'ยังขาดเรียนเป็นบางวัน',
            result: 'ปรับแผน',
            notes: 'ปรับวิธีการ พูดคุยกับผู้ปกครอง',
            evaluation_date: new Date('2024-01-18'),
          }
        ],
        last_updated: new Date('2024-01-20'),
      },
      {
        student_id: '65001', // วรเมธ
        student_name: 'นายวรเมธ รักเรียน',
        problem: 'ติดเกม เล่นเกมทั้งวัน ไม่มีเวลาเรียน สมาธิสั้น',
        goal: 'ลดเวลาการเล่นเกม เพิ่มเวลาเรียนและทำกิจกรรม',
        counseling: true,
        behavioral_contract: true,
        home_visit: true,
        referral: true,
        duration: '3 เดือน',
        responsible: `${teacher2.first_name} ${teacher2.last_name}`,
        isp_status: 'กำลังดำเนินการ',
        progress: 50,
        activities: [
          {
            activity_id: activities[1]._id,
            status: 'เข้าร่วมแล้ว',
            joined_at: new Date('2024-01-17T13:05:00'),
            notes: 'เข้าร่วมกิจกรรมพัฒนาทักษะ',
          },
          {
            activity_id: activities[2]._id,
            status: 'เข้าร่วมแล้ว',
            joined_at: new Date('2024-01-20T10:07:00'),
            notes: 'เข้าร่วมกลุ่มให้คำปรึกษา',
          },
          {
            activity_id: activities[3]._id,
            status: 'เข้าร่วมแล้ว',
            joined_at: new Date('2024-01-25T09:40:00'),
            notes: 'เข้าร่วมอบรมการจัดการความเครียด',
          }
        ],
        activities_status: {
          [activities[1]._id.toString()]: 'เข้าร่วมแล้ว',
          [activities[2]._id.toString()]: 'เข้าร่วมแล้ว',
          [activities[3]._id.toString()]: 'เข้าร่วมแล้ว',
        },
        activity_join_dates: {
          [activities[1]._id.toString()]: new Date('2024-01-17T13:05:00'),
          [activities[2]._id.toString()]: new Date('2024-01-20T10:07:00'),
          [activities[3]._id.toString()]: new Date('2024-01-25T09:40:00'),
        },
        activity_completed_dates: {},
        evaluations: [
          {
            evaluation_number: 1,
            improvement_level: 'เริ่มเห็นการเปลี่ยนแปลง',
            improvement_detail: 'เล่นเกมลดลงจาก 8 ชั่วโมง เหลือ 4-5 ชั่วโมงต่อวัน',
            result: 'ดำเนินการต่อ',
            notes: 'หากิจกรรมเสริมให้ทำ',
            evaluation_date: new Date('2024-01-19'),
          }
        ],
        last_updated: new Date('2024-01-20'),
      },
      {
        student_id: '64002', // วาสนา
        student_name: 'นางสาววาสนา รุ่งเรือง',
        problem: 'เครียดสะสม กังวลเรื่องการเรียนและการเงิน มีอาการซึมเศร้า',
        goal: 'ความเครียดลดลง สามารถจัดการอารมณ์ได้ดีขึ้น',
        counseling: true,
        behavioral_contract: false,
        home_visit: true,
        referral: true,
        duration: '3 เดือน',
        responsible: `${teacher3.first_name} ${teacher3.last_name}`,
        isp_status: 'กำลังดำเนินการ',
        progress: 55,
        activities: [
          {
            activity_id: activities[2]._id,
            status: 'เข้าร่วมแล้ว',
            joined_at: new Date('2024-01-20T10:12:00'),
            notes: 'เข้าร่วมกลุ่มให้คำปรึกษา',
          },
          {
            activity_id: activities[3]._id,
            status: 'เข้าร่วมแล้ว',
            joined_at: new Date('2024-01-25T09:45:00'),
            notes: 'เข้าร่วมอบรมการจัดการความเครียด',
          }
        ],
        activities_status: {
          [activities[2]._id.toString()]: 'เข้าร่วมแล้ว',
          [activities[3]._id.toString()]: 'เข้าร่วมแล้ว',
        },
        activity_join_dates: {
          [activities[2]._id.toString()]: new Date('2024-01-20T10:12:00'),
          [activities[3]._id.toString()]: new Date('2024-01-25T09:45:00'),
        },
        activity_completed_dates: {},
        evaluations: [
          {
            evaluation_number: 1,
            improvement_level: 'เริ่มเห็นการเปลี่ยนแปลง',
            improvement_detail: 'เริ่มผ่อนคลายมากขึ้น สามารถพูดคุยได้',
            result: 'ดำเนินการต่อ',
            notes: 'ส่งต่อพบจิตแพทย์',
            evaluation_date: new Date('2024-01-25'),
          }
        ],
        last_updated: new Date('2024-01-25'),
      },
    ]);

    // ==================== CREATE REFERRALS (ระบบส่งต่อ) ====================
    console.log('📤 Creating referrals...');
    const referrals = await Referral.create([
      {
        student_id: '66002',
        student_name: 'นางสาวจิราภา ใจดี',
        student_level: 'ปวช.1',
        student_class: 'เทคโนโลยีสารสนเทศ',
        student_number: '2',
        type: 'internal',
        target: 'ฝ่ายกิจการนักเรียน',
        reason_category: 'ด้านเศรษฐกิจ/ทุนการศึกษา',
        reason_detail: 'นักเรียนมีฐานะยากจน ขาดแคลนทุนทรัพย์ ค่าใช้จ่ายรายวันไม่เพียงพอ มีความเครียดสูง',
        actions_taken: 'ให้คำปรึกษา ประสานงานขอทุน เยี่ยมบ้าน 3 ครั้ง',
        status: 'อยู่ระหว่างดำเนินการ',
        created_at: new Date('2024-01-05'),
        updated_at: new Date('2024-02-15'),
      },
      {
        student_id: '66003',
        student_name: 'นายธนดล เข้มแข็ง',
        student_level: 'ปวช.1',
        student_class: 'เทคโนโลยีสารสนเทศ',
        student_number: '3',
        type: 'internal',
        target: 'ครูที่ปรึกษาร่วม',
        reason_category: 'ด้านพฤติกรรม/การปรับตัว',
        reason_detail: 'ขาดเรียนบ่อย ไม่สนใจการเรียน ใช้เวลากับเพื่อนมากเกินไป มีพฤติกรรมก้าวร้าว',
        actions_taken: 'ตักเตือน ทำบันทึก พูดคุยกับผู้ปกครอง 2 ครั้ง',
        status: 'อยู่ระหว่างดำเนินการ',
        created_at: new Date('2024-01-08'),
        updated_at: new Date('2024-01-18'),
      },
      {
        student_id: '65001',
        student_name: 'นายวรเมธ รักเรียน',
        student_level: 'ปวช.2',
        student_class: 'การบัญชี',
        student_number: '1',
        type: 'external',
        target: 'โรงพยาบาลจิตเวชขอนแก่น',
        reason_category: 'ด้านสุขภาพจิต/พฤติกรรม',
        reason_detail: 'ติดเกมขั้นรุนแรง มีอาการถอนเมื่อไม่ได้เล่น สมาธิสั้น ส่งผลต่อการเรียน',
        actions_taken: 'ให้คำปรึกษา ทำสัญญาพฤติกรรม เยี่ยมบ้าน 2 ครั้ง',
        status: 'อยู่ระหว่างดำเนินการ',
        created_at: new Date('2024-01-10'),
        updated_at: new Date('2024-01-20'),
      },
      {
        student_id: '64002',
        student_name: 'นางสาววาสนา รุ่งเรือง',
        student_level: 'ปวส.1',
        student_class: 'การตลาด',
        student_number: '2',
        type: 'external',
        target: 'โรงพยาบาลศรีนครินทร์',
        reason_category: 'ด้านสุขภาพจิต/พฤติกรรม',
        reason_detail: 'เครียดสะสม กังวล มีอาการซึมเศร้า ต้องได้รับการประเมินจากจิตแพทย์',
        actions_taken: 'ให้คำปรึกษา 5 ครั้ง เยี่ยมบ้าน 1 ครั้ง',
        status: 'อยู่ระหว่างดำเนินการ',
        created_at: new Date('2024-01-15'),
        updated_at: new Date('2024-01-25'),
      },
    ]);

    // ==================== CREATE COORDINATIONS (การประสานงาน) ====================
    console.log('📞 Creating coordinations...');
    await Coordination.create([
      {
        referral_id: referrals[0]._id,
        organization: 'ฝ่ายกิจการนักเรียน วิทยาลัยเทคนิคขอนแก่น',
        contact_person: 'อาจารย์ประสานงานทุน',
        channel: 'โทรศัพท์/ประชุม',
        details: 'แจ้งข้อมูลนักเรียนเพื่อขอรับทุนการศึกษากรณีฉุกเฉิน ส่งเอกสารหลักฐาน',
        agreement: 'ให้นักเรียนกรอกใบสมัครทุนและส่งเอกสารภายใน 3 วัน',
        coordination_date: new Date('2024-01-07'),
        created_at: new Date('2024-01-07'),
      },
      {
        referral_id: referrals[0]._id,
        organization: 'มูลนิธิช่วยเหลือนักเรียน',
        contact_person: 'คุณสมศรี ผู้ประสานงาน',
        channel: 'โทรศัพท์',
        details: 'ประสานงานขอทุนเพิ่มเติม แจ้งข้อมูลนักเรียน',
        agreement: 'ส่งเอกสารให้พิจารณา ติดตามผลอีก 2 สัปดาห์',
        coordination_date: new Date('2024-01-12'),
        created_at: new Date('2024-01-12'),
      },
      {
        referral_id: referrals[1]._id,
        organization: 'ครูที่ปรึกษาร่วม',
        contact_person: 'ครูมาลี ดูแลดี',
        channel: 'พบปะโดยตรง',
        details: 'หารือแนวทางช่วยเหลือนักเรียน ร่วมกันวางแผน',
        agreement: 'ช่วยกันติดตามพฤติกรรม และให้คำปรึกษาสัปดาห์ละครั้ง',
        coordination_date: new Date('2024-01-10'),
        created_at: new Date('2024-01-10'),
      },
      {
        referral_id: referrals[1]._id,
        organization: 'ผู้ปกครองนักเรียน',
        contact_person: 'คุณประเสริฐ เข้มแข็ง',
        channel: 'โทรศัพท์',
        details: 'แจ้งพฤติกรรมของนักเรียนที่โรงเรียน ขอความร่วมมือ',
        agreement: 'ผู้ปกครองจะช่วยดูแลและติดตามพฤติกรรมที่บ้าน',
        coordination_date: new Date('2024-01-12'),
        created_at: new Date('2024-01-12'),
      },
      {
        referral_id: referrals[2]._id,
        organization: 'โรงพยาบาลจิตเวชขอนแก่น',
        contact_person: 'นักจิตวิทยา คุณธนพล',
        channel: 'โทรศัพท์/ส่งเอกสาร',
        details: 'ส่งต่อนักเรียนเพื่อรับการประเมินและบำบัด ส่งประวัติและข้อมูล',
        agreement: 'นัดหมายวันที่ 25 ม.ค. 67 เวลา 9.00 น.',
        coordination_date: new Date('2024-01-15'),
        created_at: new Date('2024-01-15'),
      },
      {
        referral_id: referrals[3]._id,
        organization: 'โรงพยาบาลศรีนครินทร์',
        contact_person: 'จิตแพทย์',
        channel: 'หนังสือราชการ',
        details: 'ส่งต่อนักเรียนเพื่อรับการประเมินทางจิตเวช',
        agreement: 'รอคิวพบจิตแพทย์ ประมาณ 2 สัปดาห์',
        coordination_date: new Date('2024-01-18'),
        created_at: new Date('2024-01-18'),
      },
    ]);

    // ==================== CREATE FOLLOW-UPS (การติดตามผล) ====================
    console.log('📊 Creating follow-ups...');
    await FollowUp.create([
      {
        referral_id: referrals[0]._id,
        follow_date: new Date('2024-01-15'),
        result: 'พฤติกรรมดีขึ้น/ปัญหาคลี่คลาย',
        notes: 'นักเรียนได้รับทุนฉุกเฉิน 5000 บาท และได้รับอาหารกลางวันฟรี',
        created_at: new Date('2024-01-15'),
      },
      {
        referral_id: referrals[0]._id,
        follow_date: new Date('2024-01-20'),
        result: 'พฤติกรรมดีขึ้น/ปัญหาคลี่คลาย',
        notes: 'นักเรียนมีรอยยิ้ม สดใสขึ้น มากินอาหารกลางวันทุกวัน เรียนดีขึ้น',
        created_at: new Date('2024-01-20'),
      },
      {
        referral_id: referrals[0]._id,
        follow_date: new Date('2024-02-15'),
        result: 'พฤติกรรมดีขึ้น/ปัญหาคลี่คลาย',
        notes: 'นักเรียนมีผลการเรียนดีขึ้น ความเครียดลดลงมาก',
        created_at: new Date('2024-02-15'),
      },
      {
        referral_id: referrals[1]._id,
        follow_date: new Date('2024-01-15'),
        result: 'พฤติกรรมคงเดิม',
        notes: 'นักเรียนยังขาดเรียนอีก 2 วัน ไม่มาเรียนวันจันทร์',
        created_at: new Date('2024-01-15'),
      },
      {
        referral_id: referrals[1]._id,
        follow_date: new Date('2024-01-18'),
        result: 'พฤติกรรมคงเดิม',
        notes: 'พูดคุยกับผู้ปกครองแล้ว แต่ยังไม่ดีขึ้น',
        created_at: new Date('2024-01-18'),
      },
      {
        referral_id: referrals[1]._id,
        follow_date: new Date('2024-01-25'),
        result: 'เริ่มเห็นการเปลี่ยนแปลง',
        notes: 'นักเรียนมาเรียนมากขึ้น แต่ยังขาดบางวัน',
        created_at: new Date('2024-01-25'),
      },
      {
        referral_id: referrals[2]._id,
        follow_date: new Date('2024-01-18'),
        result: 'เริ่มเห็นการเปลี่ยนแปลง',
        notes: 'ผู้ปกครองพาไปพบนักจิตวิทยาแล้ว นัดติดตามอาการ',
        created_at: new Date('2024-01-18'),
      },
      {
        referral_id: referrals[2]._id,
        follow_date: new Date('2024-01-25'),
        result: 'เริ่มเห็นการเปลี่ยนแปลง',
        notes: 'ได้พบจิตแพทย์ ได้รับคำแนะนำ เริ่มปรับพฤติกรรม',
        created_at: new Date('2024-01-25'),
      },
      {
        referral_id: referrals[2]._id,
        follow_date: new Date('2024-02-10'),
        result: 'พฤติกรรมดีขึ้น/ปัญหาคลี่คลาย',
        notes: 'เล่นเกมลดลง เริ่มสนใจการเรียนมากขึ้น',
        created_at: new Date('2024-02-10'),
      },
      {
        referral_id: referrals[3]._id,
        follow_date: new Date('2024-01-25'),
        result: 'เริ่มเห็นการเปลี่ยนแปลง',
        notes: 'ได้พบจิตแพทย์ ได้รับการประเมินและคำแนะนำ',
        created_at: new Date('2024-01-25'),
      },
      {
        referral_id: referrals[3]._id,
        follow_date: new Date('2024-02-05'),
        result: 'เริ่มเห็นการเปลี่ยนแปลง',
        notes: 'อาการดีขึ้นตามลำดับ ยังคงติดตาม',
        created_at: new Date('2024-02-05'),
      },
    ]);

    console.log('\n✅ Seed data created successfully!');
    console.log('📊 Summary:');
    console.log(`   - Users: ${await User.countDocuments()}`);
    console.log(`   - Majors: ${await Major.countDocuments()}`);
    console.log(`   - Students: ${await Student.countDocuments()}`);
    console.log(`   - Activities: ${await Activity.countDocuments()}`);
    console.log(`   - Learn Plans: ${await Learn.countDocuments()}`);
    console.log(`   - Problems: ${await Problem.countDocuments()}`);
    console.log(`   - Referrals: ${await Referral.countDocuments()}`);
    console.log(`   - Coordinations: ${await Coordination.countDocuments()}`);
    console.log(`   - FollowUps: ${await FollowUp.countDocuments()}`);
    
    console.log('\n🔐 Login credentials:');
    console.log(`   - Admin: admin@school.ac.th / 1234`);
    console.log(`   - Teacher 1 (ปวช.1 เทคโนโลยีสารสนเทศ): somsak@school.ac.th / 1234`);
    console.log(`   - Teacher 2 (ปวช.2 การบัญชี): malee@school.ac.th / 1234`);
    console.log(`   - Teacher 3 (ปวส.1 การตลาด): prasert@school.ac.th / 1234`);
    console.log(`   - Executive: executive@school.ac.th / 1234`);
    console.log(`   - Committee: committee@school.ac.th / 1234`);

  } catch (error) {
    console.error('❌ Error seeding data:', error);
  } finally {
    await mongoose.disconnect();
    console.log('🔌 Disconnected from MongoDB');
  }
}

// Run the seed function
seed();