// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";

import BootstrapClient from "./bootstrap";
import Header from "./components/Header";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import Footer from "./components/Footer";
import { SessionProvider } from "./components/SessionProvider";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const pathname = headersList.get("x-pathname") || "";

  // ตรวจสอบว่าเป็นหน้า login หรือ register หรือไม่
  const isAuthPage = pathname === "/login" || pathname === "/register";

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <BootstrapClient />
        <SessionProvider>
          <div className="container-fluid p-0">
            {!isAuthPage && (
              <>
                <Header />
                <Navbar />
              </>
            )}
            <div className="row g-0">
              {!isAuthPage && (
                <div className="col-md-3 col-lg-2">
                  <Sidebar />
                </div>
              )}
              <div className={!isAuthPage ? "col-md-9 col-lg-10 p-4" : "col-12"}>
                {children}
              </div>
            </div>
            {!isAuthPage && <Footer />}
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}